### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by don-tpanic** [lrank/Domain_Robust_Text_Representation#1]
Thanks for sharing the code! Much appreciated. Just wonder if you have the code for getting the results of SCL_MI? As based on your paper, your training setting is different from Blitzer's, yet the results you show in the table 3. are identical to the results on his paper. I wonder if I missed anything here hope you could clarify it for me.

Thanks again.

**Comment by lrank** [comment]
Hi, don-tpanic.

You are right that the setting of our paper is different from Bilter's. Since we use the same test data, our results are still comparable even the training resource and settings are different.
As for your concern, I am sorry I do not have the code of SCL, and yes, the numbers are the same.

Thanks you
